packages:
  - packages/*
  - playground

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@iconify-json/codicon': ^1.2.31
  '@iconify-json/lucide': ^1.2.72
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/radix-icons': ^1.2.5
  '@iconify-json/twemoji': ^1.2.4
  '@iconify-json/vscode-icons': ^1.2.33
  '@nuxt/eslint': ^1.10.0
  '@nuxt/kit': ^4.2.1
  '@nuxt/ui': ^4.1.0
  '@shikijs/langs': ^3.15.0
  '@shikijs/themes': ^3.15.0
  '@types/node': ^22.19.0
  '@types/picomatch': ^4.0.2
  '@vitejs/devtools': 0.0.0-alpha.10
  '@vitejs/devtools-kit': 0.0.0-alpha.10
  '@vueuse/core': ^14.0.0
  '@vueuse/nuxt': ^14.0.0
  ansis: ^4.2.0
  bumpp: ^10.3.1
  consola: ^3.4.2
  eslint: ^9.39.1
  eslint-plugin-oxlint: ^1.26.0
  get-port-please: ^3.2.0
  gunshi: ^0.26.3
  lint-staged: ^16.2.6
  nuxt: ^4.2.1
  oxlint: ^1.26.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  shiki: ^3.15.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.17
  tsdown: ^0.16.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: npm:rolldown-vite@^7.2.2
  vue: ^3.5.24
  vue-router: ^4.6.3
