packages:
  - playground
  - client

catalog:
  '@clack/prompts': ^1.0.1
  '@iconify-json/codicon': ^1.2.44
  '@iconify-json/lucide': ^1.2.90
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/radix-icons': ^1.2.6
  '@iconify-json/twemoji': ^1.2.5
  '@iconify-json/vscode-icons': ^1.2.42
  '@nuxt/kit': ^4.3.1
  '@nuxt/ui': ^4.4.0
  '@shikijs/langs': ^3.22.0
  '@shikijs/themes': ^3.22.0
  '@types/node': ^22.19.11
  '@types/picomatch': ^4.0.2
  '@vitejs/devtools': ^0.0.0-alpha.31
  '@vitejs/devtools-kit': ^0.0.0-alpha.31
  '@vitejs/devtools-rpc': ^0.0.0-alpha.31
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  ansis: ^4.2.0
  bumpp: ^10.4.1
  get-port-please: ^3.2.0
  gunshi: ^0.28.0
  h3: 2.0.1-rc.14
  lint-staged: ^16.2.7
  nuxt: ^4.3.1
  oxfmt: ^0.32.0
  oxlint: ^1.47.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  shiki: ^3.22.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.18
  tinyexec: ^1.0.2
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^8.0.0-beta.14
  vue: ^3.5.28
  vue-router: ^5.0.2

catalogMode: prefer

ignoreWorkspaceRootCheck: true

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
