packages:
  - packages/*
  - playground

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@iconify-json/codicon': ^1.2.31
  '@iconify-json/lucide': ^1.2.72
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/radix-icons': ^1.2.5
  '@iconify-json/vscode-icons': ^1.2.33
  '@nuxt/eslint': ^1.10.0
  '@nuxt/kit': ^4.2.0
  '@nuxt/ui': ^4.1.0
  '@shikijs/langs': ^3.14.0
  '@shikijs/themes': ^3.14.0
  '@types/node': ^22.15.17
  '@types/picomatch': ^4.0.2
  '@vitejs/devtools': 0.0.0-alpha.10
  '@vitejs/devtools-kit': 0.0.0-alpha.10
  '@vueuse/core': ^14.0.0
  '@vueuse/nuxt': ^14.0.0
  ansis: ^4.0.0
  bumpp: ^10.1.0
  consola: ^3.4.2
  eslint: ^9.39.1
  eslint-plugin-oxlint: ^1.1.0
  get-port-please: ^3.1.2
  gunshi: ^0.26.3
  lint-staged: ^16.0.0
  nuxt: 4.1.2
  oxlint: ^1.26.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  shiki: ^3.14.0
  simple-git-hooks: ^2.13.0
  tailwindcss: ^4.1.16
  tsdown: ^0.11.9
  tsx: ^4.19.4
  typescript: ^5.8.3
  vite: npm:rolldown-vite@^7.1.20
  vue: ^3.5.22
  vue-router: ^4.6.3
